name: assignment3

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Log Workflow Start Time
        run: |
          echo "$(date -Iminutes)" >> log.txt
          echo "Gavriel Cohen, Mikhail Yagudaev" >> log.txt
      - name: Build the Docker Image
        run: |
          docker build -t book-service ./books && echo "image successfully built" >> log.txt || (echo "image not able to be built" >> log.txt && exit 1)
          docker save book-service -o book-service-image.tar
      - name: Upload Image to GitHub
        uses: actions/upload-artifact@v3
        with:
          name: book-service-image
          path: book-service-image.tar
      - name: Upload Log File
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: log-file
          path: log.txt

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Download Log File
        uses: actions/download-artifact@v3
        with:
          name: log-file
          path: .
      - name: Download Docker Image
        uses: actions/download-artifact@v3
        with:
          name: book-service-image
          path: .
      - name: Load Docker Image
        run: docker load --input book-service-image.tar
      - name: Run Docker Container
        run: docker compose up -d
      - name: Check Container Status
        if: always()
        run: |
          ls
          running=$(docker-compose ps --services --filter "status=running")
          services=$(docker-compose ps --services)
          if [ "$running" == "$services" ]; then
            echo "Container up and running" >> log1.txt
          else
            echo "Container failed to run" >> log1.txt
            exit 1
          fi
      - name: Upload Log File
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: log-file
          path: log1.txt
          

