name: assignment3

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: docker build -t books-service ./books

      - name: Log Build Success
        run: |
          echo "$(date -Iminutes)" > log.txt
          echo "Your Name" >> log.txt
          echo "image successfully built" >> log.txt

      - name: Upload build logs
        uses: actions/upload-artifact@v3
        with:
          name: build-logs
          path: log.txt

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Compose
        run: docker-compose -f docker-compose.yml up -d --build

      - name: Run Tests
        run: |
          docker-compose exec books pytest -v tests/assn3_tests.py | tee assn3_test_results.txt
          if [ ${PIPESTATUS[0]} -eq 0 ]; then
            echo "tests succeeded" >> log.txt
          else
            echo "tests failed" >> log.txt
        continue-on-error: true

      - name: Stop Docker Compose
        run: docker-compose down

      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
