name: assignment3

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: log text
        run: |
          echo "$(date -Iminutes)" >> log.txt
          echo "Gavriel Cohen, Mikhail Yagudaev" >> log.txt
      - name: upload log file
        uses: actions/upload-artifact@v4
        with:
          name: log file
          path: log.txt
