name: assignment3

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: log text
        run: |
          echo 'hi' >> log.txt
      - name: upload log file
        uses: actions/upload-artifact@v4
        with:
          name: log file
          path: log.txt
